### ISSUE TITLE
panic: runtime error: invalid memory address

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx-release-version#5]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x633c81]

goroutine 1 [running]:
github.com/jenkins-x/jx-release-version/vendor/github.com/hashicorp/go-version.(*Version).String(0x0, 0x1b, 0x0)
	/Users/jr/go/src/github.com/jenkins-x/jx-release-version/vendor/github.com/hashicorp/go-version/version.go:307 +0x51
main.getNewVersionFromTag(0x0, 0x6eda03, 0x1, 0x0, 0x0, 0x0, 0x0, 0x7fe72ffca260, 0x0, 0x40e418, ...)
	/Users/jr/go/src/github.com/jenkins-x/jx-release-version/main.go:244 +0x18c
main.main()
	/Users/jr/go/src/github.com/jenkins-x/jx-release-version/main.go:52 +0x21d
```

**Comment by rawlingsj** [comment]
fixed in https://github.com/jenkins-x/jx-release-version/commit/c48e1dfd2df7a17c5d53b1e2db5be83f1f2bdad3
